INSERT INTO measure_unit (id, singular_name, plural_name)
VALUES (1, 'Unidad', 'Unidades');

INSERT INTO supplier (id, name)
VALUES (1, '111'),
       (2, '1A'),
       (3, 'AFICHES'),
       (4, 'ANEXO'),
       (5, 'CARACAS'),
       (6, 'CARACAS CACHUCHAS'),
       (7, 'CARACAS CALI'),
       (8, 'CARACAS DETRÁS'),
       (9, 'CARACAS MASCOTAS'),
       (10, 'CARACAS PLANTILLAS'),
       (11, 'CARLOS'),
       (12, 'CARNETS'),
       (13, 'CAROLINA'),
       (14, 'CESTERIA'),
       (15, 'COSMETICOS'),
       (16, 'DELFIN'),
       (17, 'DESECHABLES'),
       (18, 'DUQUE'),
       (19, 'EDUAR'),
       (20, 'ELECTRICOS'),
       (21, 'ESFEROS SJ'),
       (22, 'ESTELLA'),
       (23, 'FABIOLA PAJARERA'),
       (24, 'HALLOWEEN'),
       (25, 'HILOS'),
       (26, 'INDIVIDUALES'),
       (27, 'JAIME'),
       (28, 'JHON'),
       (29, 'JHON 1ER PISO'),
       (30, 'JUGUETES SV2 PISO'),
       (31, 'LEIDER'),
       (32, 'LEIDY'),
       (33, 'LER'),
       (34, 'LLAVEROS'),
       (35, 'LUISA'),
       (36, 'LUZ'),
       (37, 'MALETAS TEMPORADA'),
       (38, 'MAQUETAS'),
       (39, 'MERCEDES'),
       (40, 'MILENA'),
       (41, 'MILENIO'),
       (42, 'NANCY'),
       (43, 'NAVIDAD'),
       (44, 'OBRAS'),
       (45, 'OLGA'),
       (46, 'PAJARERA'),
       (47, 'PAOLA'),
       (48, 'PARAISO'),
       (49, 'PARQUEADERO'),
       (50, 'PELUCHES'),
       (51, 'QUIMICOS'),
       (52, 'RAYO'),
       (53, 'SUPER R4'),
       (54, 'SURTIDOR'),
       (55, 'SURTIPIÑATAS'),
       (56, 'VELADAS'),
       (57, 'VELAS'),
       (58, 'VICTOR'),
       (59, 'YAMILE');
